# Generated by Django 3.1.3 on 2021-06-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=13)),
                ("email_address", models.EmailField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="persons_on_parent",
                        to="person.person",
                    ),
                ),
            ],
            options={"db_table": "person",},
        ),
    ]
